### ISSUE TITLE
Dogs pushed into portals spam errors in log

### ISSUE THREAD

**Issue by Absentee23** [Cube-Space/geSuit#46]
Dogs (this one was owned/named) pushed into (water, likely the same as lava) portals spam the spigot log with this:
http://pastebin.com/VmBhK6qE

May happen with other mobs/entities, but I haven't tested thoroughly.

Also, do you know if there's been any fix yet for the bukkit bug that was preventing a fix for lava portal damage?

**Comment by jimmikaelkael** [comment]
This shouldn't happen as the DamageEvent listener exclude entities that are not players:
!(event.getEntity() instanceof Player)

The log is mentionning a PlayerEntity, are you walking in the portal too when pushing the dog ?

EDIT:Also, how are you pushing the dog ? by damaging it ?

EDIT2: This issue is the same as issue #40

**Comment by Absentee23** [comment]
Ah yes, you are correct, it was when a player was trying to push it out of the portal without entering it that it threw the errors, and it is the same as that issue. Closing this one then.
